/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geist", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      colors: {
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "outline-variant": "var(--outline-variant)",
        "surface-container-low": "var(--surface-container-low)",
        primary: "var(--primary)",
        "surface-variant": "var(--surface-variant)",
        surface: "var(--surface)",
        "secondary-container": "var(--secondary-container)",
        tertiary: "var(--tertiary)",
        error: "var(--error)",
        "error-container": "var(--error-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-error-container": "var(--on-error-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-tint": "var(--surface-tint)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-dim": "var(--surface-dim)",
        "on-secondary": "var(--on-secondary)",
        outline: "var(--outline)",
        "inverse-surface": "var(--inverse-surface)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-tertiary": "var(--on-tertiary)",
        "on-primary": "var(--on-primary)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        secondary: "var(--secondary)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "primary-fixed": "var(--primary-fixed)",
        "surface-container": "var(--surface-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-background": "var(--on-background)",
        "primary-container": "var(--primary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "on-surface": "var(--on-surface)",
        "on-error": "var(--on-error)",
        background: "var(--background)",
        "inverse-on-surface": "var(--inverse-on-surface)",
      },
    },
  },
};